### ISSUE TITLE
README.md suggestions for N00bs

### ISSUE THREAD

**Issue by mikezawitkowski** [smoningi/SF-Environment-Benchmark#21]
I was wondering if we could add a getting started section to the README.md? Something like 

step 1. clone repo
step 2. start server
step 3. profit!

**Comment by thfield** [comment]
excellet suggestions (i say as i was sitting next to you, suggesting you put them in)
I'll work on this, along with some general spring cleaning

**Comment by thfield** [comment]
I've added some instructions, they probably should be flushed out (fleshed out?) more, but I'm going to close this issue for now
